-- 031 — MÍDIA (podcasts, videocasts, videoaulas) com player embutido
-- Modelo unificado: o admin cola um link (YouTube/Spotify), define título,
-- legenda e ordem; o app embute o player (sem redirecionar). Mesmo padrão de
-- admin das notícias (RLS: público lê, só admin escreve).

create table if not exists public.media (
  id          bigint generated by default as identity primary key,
  tipo        text not null check (tipo in ('podcast','videocast','videoaula')),
  titulo      text not null,
  legenda     text,
  url         text not null,          -- link original (YouTube/Spotify/etc.)
  ordem       int  not null default 0,-- ordenação (asc); admin reordena
  created_at  timestamptz default now()
);
create index if not exists media_tipo_ordem_idx on public.media (tipo, ordem);

alter table public.media enable row level security;

drop policy if exists media_public_read on public.media;
create policy media_public_read on public.media
  for select using (true);

drop policy if exists media_admin_write on public.media;
create policy media_admin_write on public.media
  for all using (public.is_admin()) with check (public.is_admin());
